# Generated by Django 5.2.7 on 2025-10-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Profile',
        ),
    ]
