# Generated by Django 5.2.8 on 2025-11-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupée'), ('maintenance', 'En maintenance')], default='available', max_length=20),
        ),
    ]
