# Generated by Django 5.2.8 on 2025-11-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_payment_created_by_reservation_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
    ]
