# Generated by Django 5.2.8 on 2025-11-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('commune', models.CharField(max_length=100, verbose_name='Commune')),
                ('avenue', models.CharField(max_length=100, verbose_name='Avenue')),
                ('quarter', models.CharField(max_length=100, verbose_name='Quartier')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': "Information de l'entreprise",
                'verbose_name_plural': "Informations de l'entreprise",
            },
        ),
    ]
