# Generated by Django 5.2.8 on 2025-11-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='currency',
            field=models.CharField(choices=[('USD', 'Dollar américain (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Livre sterling (GBP)'), ('CDF', 'Franc congolais (CDF)'), ('XAF', 'Franc CFA (XAF)'), ('ZAR', 'Rand sud-africain (ZAR)'), ('NGN', 'Naira nigérian (NGN)'), ('KES', 'Shilling kényan (KES)'), ('TZS', 'Shilling tanzanien (TZS)'), ('UGX', 'Shilling ougandais (UGX)'), ('RWF', 'Franc rwandais (RWF)'), ('MAD', 'Dirham marocain (MAD)'), ('XOF', 'Franc CFA BCEAO (XOF)')], default='CDF', max_length=3, verbose_name='Devise'),
        ),
    ]
